version: "3"
services:
  api:
    build: ./api
    ports:
      - "6000:6000"
    networks:
      - app-network

  etl:
    build: ./etl
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge